### ISSUE TITLE
Replicating ZSSAR results

### ISSUE THREAD

**Issue by dominickrei** [EHZ9NIWI7/MSF-GZSSAR#1]
Hello, thank you for the work and code!

My goal is to reproduce the ZSSAR results seen in your paper's Table 2, but the code here seems to only perform GZSSAR. Is it possible to perform ZSSAR using this code or does it only contain the GZSSAR implementation? Thank you for any help.

**Comment by EHZ9NIWI7** [comment]
> Hello, thank you for the work and code!
> 
> My goal is to reproduce the ZSSAR results seen in your paper's Table 2, but the code here seems to only perform GZSSAR. Is it possible to perform ZSSAR using this code or does it only contain the GZSSAR implementation? Thank you for any help.

**Comment by EHZ9NIWI7** [comment]
> Hello, thank you for the work and code!
> 
> My goal is to reproduce the ZSSAR results seen in your paper's Table 2, but the code here seems to only perform GZSSAR. Is it possible to perform ZSSAR using this code or does it only contain the GZSSAR implementation? Thank you for any help.

The code performs both ZSSAR and GZSSAR. If you just want to perform ZSSAR, please modify the code in the 'run__.sh' file, keeping the code for Stage-1 and commenting out the code for the subsequent stages. （The code for ZSL testing can be found in lines 257-275 of the 'train.py' file.）

**Comment by dominickrei** [comment]
Thank you!
